ANIMEQUOTE = (
 "There are days when nothing goes right. There are days when you stumble and fall. There are days when you just want to cry. To cry a lot. To sleep a lot. Or even eat a lot. It’s alright, as long as you pick yourself up again. – Yuki Takeya (Gakkougurashi!)",
"Excuse me but are you by any chance the oddball in your family?– Ash Ketchum",
"The world isn't perfect. But it's there for us, doing the best it can....that's what makes it so damn beautiful.~ Roy Mustang (Full Metal Alchemist)",
"To know sorrow is not terrifying. What is terrifying is to know you can't go back to happiness you could have.~ Matsumoto Rangiku (Bleach)",
"Those who stand at the top determine what's wrong and what's right! This very place is neutral ground! Justice will prevail, you say? But of course it will! Whoever wins this war becomes justice!~ Don Quixote Doflamingo (One Piece)",
"Fear is freedom! Subjugation is liberation! Contradiction is truth! Those are the facts of this world! And you will all surrender to them, you pigs in human clothing!~ Satsuki Kiryuuin (Kill la Kill)",
"I am the hope of the universe. I am the answer to all living things that cry out for peace. I am protector of the innocent. I am the light in the darkness. I am truth. Ally to good! Nightmare to you!~ Son Goku (Dragon Ball Z)",
"Religion, ideology, resources, land, spite, love or just because… No matter how pathetic the reason, it’s enough to start war. War will never cease to exist… reasons can be thought up after the fact… Human nature pursues strife.~ Paine (Naruto Shippuden)",
"People, who can’t throw something important away, can never hope to change anything.~ Armin Arlert (Shingeki no Kyojin / Attack on Titan)",
"I want you to be happy. I want you to laugh a lot. I don’t know what exactly I’ll be able to do for you, but I’ll always be by your side.~ Kagome (InuYasha)",
"Thinking you’re no-good and worthless is the worst thing you can do~ Nobito (Doraemon)"  
"Don’t give up, there’s no shame in falling down! True shame is to not stand up again!~ Shintaro Midorima (Kuroko No Basket)",
"The true measure of a shinobi is not how he lives but how he dies. It’s not what they do in life but what they did before dying that proves their worth.",
"Knowing you’re different is only the beginning. If you accept these differences you’ll be able to get past them and grow even closer.– Miss Kobayashi",
"Giving up is what kills people.– Hellsing",
"No matter how deep the night, it always turns to day, eventually. – One Piece",
"A dream is worth less than nothing if you don’t have someone else to share it.~Dousan Saitou",
"You’ll only realize that you truly love someone if they already caused you enormous pain. Your enemies can never hurt you the way your loved ones can. It’s the people close to your heart that can give you the most piercing wound. Love is a double-edged sword, it can heal the wound faster or it can sink the blade even deeper.– Kenshin Himura",
"I do not need a Heaven. However, if I must go to Heaven then please, God, do not divide Heaven in two. Please do not divide the robots from the humans.– Chiisana Hoshi yo Yume",
"What you can’t accomplish alone, becomes doable when you’re with someone else.– Taichi Yaegashi",  
"Just like games, no matter how well you have things lined up in your life, there’s always something to keep you on your toes.– Junichirou Kagami",
"Do exactly as you like. That is the true meaning of pleasure. Pleasure leads to joy and joy leads to happiness.– Gilgamesh",
"If you can’t do something, then don’t. Focus on what you can do.~Shiroe",
"You can call me what you like, but I will be taking your cake.-L (from Death Note)", 
"This world is rotten. The rotten should die.― Tsugumi Ohba",
"Kakashi~Things i like and things i hate…. I don’t feel like telling you that. My dreams for the future… Never really thought about it. As for my hobbies… I have lots of hobbies",
"Most of us can relate to Shikamaru… Genius at birth, Lazy by choice",
"Yo momma’s so fat. Kakashi uses Kamui on her and runs out of Chakra",
"Any girl can be glamorous. All you have to do is stand still and look stupid",
"The moment you find the courage to give up your life for someone… would be the moment you understand love",
"Love, passion, why do we get caught up by such troublesome feelings? The mind couldn’t ever get things straight, and you lose control to know what is sensible. Deep down it’s all so vexing",
"Feelings you have for each other will not be known unless you voice them",  
"Sometimes good people make bad choices, it doesn’t mean they are bad people, it means they’re human. -Sui Ishida",
"Rather than a person who hurts others, become the person getting hurt. -Sui Ishida",
"Everybody makes a wrong turn once in a while– Ash Ketchum",
"Make your wonderful dream a reality, it will become your truth. If anyone can, it’s you.– N, Pokemon Black/White",
"It’s more important to master the cards you’re holding than to complain about the ones your opponent was dealt.– Grimsley",
"We do have a lot in common. The same earth, the same air, the same sky. Maybe if we started looking at what’s the same, instead of looking at what’s different, well, who knows?– Meowth",  
"That day four years ago… When I wasn’t needed by anyone. When nobody cared about me. When I had given up on living and was about to jump off the roof of a building… FB saved me with a single message. I didn’t care if it was a joke or not. I was just happy that somebody knew… that I was alive… that it was OK for me to live.~Moeka Kiryuu",
"Look, even if we were enemies in the world you were before, right now I’m your only ally. Even if the whole world turned against you, I would continue to be your only ally.– Moeka Kiryuu",
"When I realized, I was already on the roof of a building… I had come to hate everything. I was sick of sitting in my room holding my knees too. If nobody was going to notice or care if I died then… what’s the point in living?~Meoka Kiryuu",
"It is those who possess wisdom who are the greatest fools. History has shown us this. You could say that this is the final warning from God to those who resist.– Rintaro Okabe",
"The universe has a beginning, but no end. — Infinity. Stars, too, have their own beginnings, but their own power results in their destruction. — Finite.– Rintaro Okabe"
"Living should mean no do-overs. This is for the best.~Rintaro Okabe",
"What kind of mad scientist worries about not getting enough vegetables?– Rintaro Okabe", 
"There are two types of lies: Lies that hurt, and lies that don’t hurt.– Itaru Hashida",
"There are two things that collectors always want. The first is an item of extreme rarity. The second is colleagues to whom they can brag about their collection.- Kurapika",
"People only find me interesting because they can't tell whether I'm serious or not.- Killua Zoldyck",  
"If you want to get to know someone, find out what makes them angry.- Gon Freecss",
"It takes a mere second for treasure to turn to trash.- Hisoka Morow",
"Pranav Is God~Pranav ajay",
"Human potential for evolution is limitless. - Isaac Netero",
"You should enjoy the little detours to the fullest. Because that's where you'll find things more important than what you want.- Ging Freecss",
"You Want To Keep Everyone From Dying? That’s Naïve. It’s War. People Die-Monkey D. Luffy",
"Justice Will Prevail, You Say? But Of Course, It Will! Whoever Wins This War Becomes Justice!-Donquixote Doflamingo",
"People’s Dreams... Have No Ends -Marshall 'Blackbeard' D. Teach",
"Only I Can Call My Dream Stupid!-Roronoa Zoro",
    "Living has it own challenges. I’ll give you just one piece of advice. Don’t quit. Yes, when you die, you die. But if you give up, you’re definitely going to die. That, I am sure of. – Brittany (Hai to Gensou no Grimgar)",
    "All I Can Do Is Work Hard! That’s The Story Of My Life! - Tanjiro Kamado (Demon Slayer: Kimetsu no yaiba)",
    "You can’t sit around envying other people’s worlds. You have to go tout and change your own. – Shinichi Chiaki (Nodame Cantabile)",
    "It’s not like something is going to happen because I believe in it. Sometimes you end up worse off because you believed in something too much. There are times it’s tough to believe in something. – Eureka (Eureka Seven)",
    " I don’t think I’ll learn anything if I don’t try to do something about it on my own. – Chizuru Hishiro (ReLIFE)",
    " A dropout will beat a genius through hard work. – Rock Lee (Naruto)",
    "You guys sure are a worthless bunch. If you wanna wallow in your tears, save it for after you’ve done everything you can. – Seiya Kanie (Amagi Brilliant Park)",
    "Smile. Not for anyone else, but for yourself. Show yourself your own smile. You’ll feel better then. – Rintaro Tatewaki (Magic-Kyun! Renaissance)",
    "It may be hard right now, but you must silence those thoughts. Stop counting only those things that you have lost. What is gone, is gone. – Jinbei (One Piece)",
    "Remember this… no matter where you go, the strength of your mind and spirit is the most powerful magic of all. – Princess Emeraude (Magic Knight Rayearth)",
    "I haven’t relied on luck since the moment I was born. Everything has been the result of my choices. – Kagura Mikazuchi (Fairy Tail)",
    "If praying does not work, and words are ineffective, what’s left is to fight. – Meme Oshino (Bakemonogatari)",
    "Whether a fish lives in a clear stream or a water ditch, so long as it continues swimming forward, it will grow up beautifully. – Koro-sensei (Assassination Classroom)",
    " If you feel yourself hitting up against your limit, remember for what cause you clench your fists! Remember why you started down this path, and let that memory carry you beyond your limit. – All Might (My Hero Academia)",
    "Fear is not evil. It tells you what your weakness is. And once you know your weakness, you can become stronger, as well as kinder. – Gildarts Clive (Fairy Tail)",
    "How can you move forward if you keep regretting the past? – Edward Elric (Fullmetal Alchemist)",
    "Maybe there’s only a dark road up ahead. But you still have to believe and keep going. Believe that the stars will light your path, even a little bit. Come on, let’s go on a journey! – Kaori Miyazono (Shigatsu Wa Kimi No Uso)",
    "Although I’m weak and full of flaws, I will never stop moving forward. No matter who I am, no one other than myself will create my own existence. No matter what others may think or feel, I will still move forward as myself. – Oz Vessalius (Pandora Hearts)",
    "In this world, there’s no such thing as ‘failure’ in the first place. The one who knows the ‘ways to win’ more than anyone is also the one who’s experienced the most ‘mistakes’. In other words… You could say ‘failure’ is equal to ‘success’… Couldn’t you? – Toriko (Toriko)",
    " If you can’t do something, then don’t. Focus on what you can do. – Shiroe (Log Horizon)",
    " Life is like a tube of toothpaste. When you’ve used all the toothpaste down to the last squeeze, that’s when you’ve really lived. Live with all your might, and struggle as long as you have life. – Mion Sonozaki (Higurashi no Naku Koro ni)",
    " I won’t be defeated because I know how awful it feels to lose after doing my very best! – Sho Kazamatsuri (Whistle!)",
    "Stop pouting! You learned something valuable. Remember the lesson, not the disappointment. – Holo (Spice & Wolf)",
    "The ones who accomplish something are the fools who keep pressing onward. The ones who accomplish nothing are the wise who cease advancing. – Celica Arfonia (Rokudenashi Majutsu Koushi to Akashic Records)",
    "Just walk the path you believe in. And don’t forget, you’re the main character of your own life story! – Glenn Radars (Rokudenashi Majutsu Koushi to Akashic Records)",
    "The only one who can decide your worth.. is you. If you want to earn something, you need to reach out for it. Pro-athletes give up their teenage years to train. Business owners put up collateral to borrow money. That’s how it always works. To make your ambitions come true, you have to take risks. The larger the ambition the greater the risk. That might involve time or enough work to affect your lifespan… So make your choice. Live in peace as a wannabe or risk losing it all to reach the very top. You’re the one who needs to decide. – Jabami Yumeko (Kakegurui)",
    " The lifespan of a human is certainly way too short. That’s why you’ve got to make the most of it and live your life to the fullest. – Leone (Akame Ga Kill!)",
    "Enjoy your life today. Yesterday is gone, and the tomorrow might never come. – Takeshi Yamamoto (Katekyo Hitman Reborn!)",
    "A road is something that you make yourself. – Jotaro Kujo (JoJo’s Bizarre Adventure)",
    "No matter what you’re doing, the most essential thing is to not give up. Fail as many times as it takes. Keep trying persistantly untill you can call yourself ‘avarage’. If you can collect a nice group of avarage-level skills, that’s already above-avarage. You’ve created your own sort of ‘talent’. – Yuuji Kazami",
    "People’s lives don’t end when they die, it ends when they lose faith. – Itachi Uchiha (Naruto)",
    "If you don’t like your destiny, don’t accept it. – Naruto Uzumaki (Naruto)"
    "When you give up, that’s when the game ends.” – Mitsuyoshi Anzai (Slam Dunk)",
    "All we can do is live until the day we die. Control what we can…and fly free. – Deneil Young (Uchuu Kyoudai or Space Brothers)",
    "Forgetting is like a wound. The wound may heal, but it has already left a scar. – Monkey D. Luffy (One Piece)",
    "Giving up kills people. When people reject giving up… they finally win the right to transcend humanity. – Alucard (Hellsing)",
    "If you don’t share someone’s pain, you can never understand them. – Nagato (Naruto)",
    "Whatever you lose, you’ll find it again. But what you throw away you’ll never get back. – Himura Kenshin (Rurouni Kenshin)",
    "We don’t have to know what tomorrow holds! That’s why we can live for everything we’re worth today! – Natsu Dragneel (Fairy Tail)",
    "Being weak is nothing to be ashamed of… Staying weak is !! – Fuegoleon Vermillion (Black Clover)",
    "Reject common sense to make the impossible possible. – Simon (Tengen Toppa Gurren Lagann)"
    "If you really want to be strong… Stop caring about what your surrounding thinks of you! – Saitama (One Punch Man)",
    "Who decides limits? And based on what? You said you worked hard? Well, maybe you need to work a little harder. Is that really the limit of your strength? Could the you of tomorrow beat you today? Instead of giving in, move forward. – Saitama (One Punch Man)",
    "A person grows up when he’s able to overcome hardships. Protection is important, but there are some things that a person must learn on his own. – Jiraiya (Naruto)"
    "Hard work is worthless for those that don’t believe in themselves. – Naruto Uzumaki (Naruto)",
    "Mistakes are not shackles that halt one from stepping forward. Rather, they are that which sustain and grow one’s heart. – Mavis Vermillion (Fairy Tail)",
    "A place where someone still thinks about you is a place you can call home. – Jiraiya (Naruto)",
    "Life comes at a cost. Wouldn’t it be arrogant to die before you’ve repaid that debt?” – Yuuji Kazami (The Fruit of Grisaia / Gurizaia no Kajitsu)",
    "Vision is not what your eyes see, but an image that your brain comprehends. – Touko Aozaki (The Garden of Sinners / Kara no Kyōkai)",
    "Hatred and Sorrow are power. They are yours to control. All you have to do is to turn them into strength and use that strength to move forward. – Sebastian Michaelis (Black Butler / Kuroshitsuji)"
    "It’s not always possible to do what we want to do, but it’s important to believe in something before you actually do it. – Might Guy (Naruto)"
    "Don’t beg for things. Do it yourself, or else you won’t get anything. – Renton Thurston (Eureka Seven)",
    "Life and death are like light and shadow. They’re both always there. But people don’t like thinking about death, so subconsciously, they always look away from it. – Yato (Noragami)",
    "Moving on doesn’t mean you forget about things. It just means you have to accept what’s happened and continue living. – Erza Scarlet (Fairy Tail)",
    "If you keep on hiding your true feelings, who is going to be happy? If you are sad, you should say it out loud!” – Haruhi Fujioka (Ouran High School Host Club)"
    "You can die anytime, but living takes true courage. – Himura Kenshin (Rurouni Kenshin)",
    "Every journey begins with a single step. We just have to have patience. – Milly Thompson (Trigun)",
    "If nobody cares to accept you and wants you in this world, accept yourself and you will see that you don’t need them and their selfish ideas. – Alibaba Saluja (Universal Warriors)",
    "Don’t be upset because of what you can’t do. Do what you do best, live as carefree and optimistically as you can, because some people aren’t able to do that. – Keima Katsuragi (The World God Only Knows)",
    "If you begin to regret, you’ll dull your future decisions and let others make your choices for you. All that’s left for you then is to die. Nobody can foretell the outcome. Each decision you make holds meaning only by affecting your next decision. – Erwin Smith (Attack on Titan: Shinjeki No Kyojin)",
    "Everything has a beginning and an end. Life is just a cycle of starts and stops. There are ends we don’t desire, but they’re inevitable, we have to face them. It’s what being human is all about. – Jet Black (Cowboy Bebop)",
    "Anything can happen. No one ever thinks it will until it does. What will happen, happens. That’s how the world is. The most important thing is to not let the tragedy defeat you. To believe that you can get through it. – Kyousuke Natsume (Little Busters!)",
    "You’ll only realize that you truly love someone if they already caused you enormous pain. Your enemies can never hurt you the way your loved ones can. It’s the people close to your heart that can give you the most piercing wound. Love is a double-edged sword, it can heal the wound faster or it can sink the blade even deeper. – Himura Kenshin (Rurouni Kenshin)",
    "It is at the moment of death that humanity has value.” – Archer (Fate Series)"
    "A lesson without pain is meaningless. That’s because no one can gain without sacrificing something. But by enduring that pain and overcoming it, he shall obtain a powerful, unmatched heart. – Edward Elric (Fullmetal Alchemist: Brotherhood)",
    "Feel The Rage. The Powerful, Pure Rage Of Not Being Able To Forgive Will Become Your Unswerving Drive To Take Action. - Giyuu Tomioka (Demon Slayer: Kimetsu No Yaiba)",
    "No Matter How Many People You May Lose, You Have No Choice But To Go On Living -- No Matter How Devastating The Blows, Maybe. - Tanjiro Kamado (Demon Slayer: Kimetsu No Yaiba)"
)

