ANIMEQUOTE = (
    "There are days when nothing goes right. There are days when you stumble and fall. There are days when you just want to cry. To cry a lot. To sleep a lot. Or even eat a lot. It’s alright, as long as you pick yourself up again. – Yuki Takeya (Gakkougurashi!)",
    "Living has it own challenges. I’ll give you just one piece of advice. Don’t quit. Yes, when you die, you die. But if you give up, you’re definitely going to die. That, I am sure of. – Brittany (Hai to Gensou no Grimgar)",
    "All I Can Do Is Work Hard! That’s The Story Of My Life! - Tanjiro Kamado (Demon Slayer: Kimetsu no yaiba)",
    "You can’t sit around envying other people’s worlds. You have to go tout and change your own. – Shinichi Chiaki (Nodame Cantabile)",
    "It’s not like something is going to happen because I believe in it. Sometimes you end up worse off because you believed in something too much. There are times it’s tough to believe in something. – Eureka (Eureka Seven)",
    " I don’t think I’ll learn anything if I don’t try to do something about it on my own. – Chizuru Hishiro (ReLIFE)",
    " A dropout will beat a genius through hard work. – Rock Lee (Naruto)",
    "You guys sure are a worthless bunch. If you wanna wallow in your tears, save it for after you’ve done everything you can. – Seiya Kanie (Amagi Brilliant Park)",
    "Smile. Not for anyone else, but for yourself. Show yourself your own smile. You’ll feel better then. – Rintaro Tatewaki (Magic-Kyun! Renaissance)",
    "It may be hard right now, but you must silence those thoughts. Stop counting only those things that you have lost. What is gone, is gone. – Jinbei (One Piece)",
    "Remember this… no matter where you go, the strength of your mind and spirit is the most powerful magic of all. – Princess Emeraude (Magic Knight Rayearth)",
    "I haven’t relied on luck since the moment I was born. Everything has been the result of my choices. – Kagura Mikazuchi (Fairy Tail)",
    "If praying does not work, and words are ineffective, what’s left is to fight. – Meme Oshino (Bakemonogatari)",
    "Whether a fish lives in a clear stream or a water ditch, so long as it continues swimming forward, it will grow up beautifully. – Koro-sensei (Assassination Classroom)",
    " If you feel yourself hitting up against your limit, remember for what cause you clench your fists! Remember why you started down this path, and let that memory carry you beyond your limit. – All Might (My Hero Academia)",
    "Fear is not evil. It tells you what your weakness is. And once you know your weakness, you can become stronger, as well as kinder. – Gildarts Clive (Fairy Tail)",
    "How can you move forward if you keep regretting the past? – Edward Elric (Fullmetal Alchemist)",
    "Maybe there’s only a dark road up ahead. But you still have to believe and keep going. Believe that the stars will light your path, even a little bit. Come on, let’s go on a journey! – Kaori Miyazono (Shigatsu Wa Kimi No Uso)",
    "Although I’m weak and full of flaws, I will never stop moving forward. No matter who I am, no one other than myself will create my own existence. No matter what others may think or feel, I will still move forward as myself. – Oz Vessalius (Pandora Hearts)",
    "In this world, there’s no such thing as ‘failure’ in the first place. The one who knows the ‘ways to win’ more than anyone is also the one who’s experienced the most ‘mistakes’. In other words… You could say ‘failure’ is equal to ‘success’… Couldn’t you? – Toriko (Toriko)",
    " If you can’t do something, then don’t. Focus on what you can do. – Shiroe (Log Horizon)",
    " Life is like a tube of toothpaste. When you’ve used all the toothpaste down to the last squeeze, that’s when you’ve really lived. Live with all your might, and struggle as long as you have life. – Mion Sonozaki (Higurashi no Naku Koro ni)",
    " I won’t be defeated because I know how awful it feels to lose after doing my very best! – Sho Kazamatsuri (Whistle!)",
    "Stop pouting! You learned something valuable. Remember the lesson, not the disappointment. – Holo (Spice & Wolf)",
    "The ones who accomplish something are the fools who keep pressing onward. The ones who accomplish nothing are the wise who cease advancing. – Celica Arfonia (Rokudenashi Majutsu Koushi to Akashic Records)",
    "Just walk the path you believe in. And don’t forget, you’re the main character of your own life story! – Glenn Radars (Rokudenashi Majutsu Koushi to Akashic Records)",
    "The only one who can decide your worth.. is you. If you want to earn something, you need to reach out for it. Pro-athletes give up their teenage years to train. Business owners put up collateral to borrow money. That’s how it always works. To make your ambitions come true, you have to take risks. The larger the ambition the greater the risk. That might involve time or enough work to affect your lifespan… So make your choice. Live in peace as a wannabe or risk losing it all to reach the very top. You’re the one who needs to decide. – Jabami Yumeko (Kakegurui)",
    " The lifespan of a human is certainly way too short. That’s why you’ve got to make the most of it and live your life to the fullest. – Leone (Akame Ga Kill!)",
    "Enjoy your life today. Yesterday is gone, and the tomorrow might never come. – Takeshi Yamamoto (Katekyo Hitman Reborn!)",
    "A road is something that you make yourself. – Jotaro Kujo (JoJo’s Bizarre Adventure)",
    "No matter what you’re doing, the most essential thing is to not give up. Fail as many times as it takes. Keep trying persistantly untill you can call yourself ‘avarage’. If you can collect a nice group of avarage-level skills, that’s already above-avarage. You’ve created your own sort of ‘talent’. – Yuuji Kazami",
    "People’s lives don’t end when they die, it ends when they lose faith. – Itachi Uchiha (Naruto)",
    "If you don’t like your destiny, don’t accept it. – Naruto Uzumaki (Naruto)"
    "When you give up, that’s when the game ends.” – Mitsuyoshi Anzai (Slam Dunk)",
    "All we can do is live until the day we die. Control what we can…and fly free. – Deneil Young (Uchuu Kyoudai or Space Brothers)",
    "Forgetting is like a wound. The wound may heal, but it has already left a scar. – Monkey D. Luffy (One Piece)",
    "Giving up kills people. When people reject giving up… they finally win the right to transcend humanity. – Alucard (Hellsing)",
    "If you don’t share someone’s pain, you can never understand them. – Nagato (Naruto)",
    "Whatever you lose, you’ll find it again. But what you throw away you’ll never get back. – Himura Kenshin (Rurouni Kenshin)",
    "We don’t have to know what tomorrow holds! That’s why we can live for everything we’re worth today! – Natsu Dragneel (Fairy Tail)",
    "Being weak is nothing to be ashamed of… Staying weak is !! – Fuegoleon Vermillion (Black Clover)",
    "Reject common sense to make the impossible possible. – Simon (Tengen Toppa Gurren Lagann)"
    "If you really want to be strong… Stop caring about what your surrounding thinks of you! – Saitama (One Punch Man)",
    "Who decides limits? And based on what? You said you worked hard? Well, maybe you need to work a little harder. Is that really the limit of your strength? Could the you of tomorrow beat you today? Instead of giving in, move forward. – Saitama (One Punch Man)",
    "A person grows up when he’s able to overcome hardships. Protection is important, but there are some things that a person must learn on his own. – Jiraiya (Naruto)"
    "Hard work is worthless for those that don’t believe in themselves. – Naruto Uzumaki (Naruto)",
    "Mistakes are not shackles that halt one from stepping forward. Rather, they are that which sustain and grow one’s heart. – Mavis Vermillion (Fairy Tail)",
    "A place where someone still thinks about you is a place you can call home. – Jiraiya (Naruto)",
    "Life comes at a cost. Wouldn’t it be arrogant to die before you’ve repaid that debt?” – Yuuji Kazami (The Fruit of Grisaia / Gurizaia no Kajitsu)",
    "Vision is not what your eyes see, but an image that your brain comprehends. – Touko Aozaki (The Garden of Sinners / Kara no Kyōkai)",
 
)

